"""Convert a self-play replay_buffer.pkl(.gz) into the mmap layout expected
by run_supervised_pretraining.py's --data-dir loader.

Background — D1-partial enablement (2026-05-26): the B1+B2+B3 run preserved
a 12MB compressed buffer with ~100K (state, MCTS visit distribution, MCTS
root value) tuples generated by the strong warm-start (best_supervised.pt)
across 5 self-play iters. The pretrain script's loader at
scripts/run_supervised_pretraining.py:97-114 expects:

  data-dir/states.npy           (N, C, 11, 11) float32
  data-dir/values.npy           (N,)           float32
  data-dir/policies.npy         (N, 7433)      float16/float32  (soft targets)
    OR
  data-dir/policy_indices.npy   (N,)           int32            (argmax targets)

The buffer format (per inspection of yinsh_ml/training/trainer.py's
ReplayBuffer) is a dict with keys: states (list of 15×11×11 float32),
move_probs (list of 7433 float16 — soft distributions), values (list of
float), plus phases / move_numbers metadata. This script stacks them into
mmap-ready npy files in a target directory.

Usage:
    python scripts/convert_replay_buffer_to_mmap.py \\
        --buffer experiments/branchB1B2B3_run_2026-05-26/full_run_dir/20260525_233508/replay_buffer.pkl.gz \\
        --output expert_games/b1b2b3_buffer_mmap/ \\
        --policy-target soft

Then:
    python scripts/run_supervised_pretraining.py \\
        --data-dir expert_games/b1b2b3_buffer_mmap/ \\
        --use-enhanced-encoding \\
        --value-head-type spatial \\
        --epochs 6 --batch-size 512 --lr 1e-3 \\
        --output-dir models/d1_partial_b1b2b3_pretrain

Why this is the cheap probe: the buffer already exists (no 10-15h
generation cost). 100K samples is ~1.3 yngine_volume corpus-equivalent
(yngine has ~13M positions but at lower per-position diversity from
expert games). The probe tells us whether MCTS-target pretrain ON A
STRONG-TEACHER CORPUS lifts the value head out of the 0.636 VAcc
plateau — which is the load-bearing question for D1's full 100K run.
"""

from __future__ import annotations

import argparse
import gzip
import logging
import pickle
import sys
import time
from pathlib import Path
from typing import Any, Dict, List

import numpy as np

logger = logging.getLogger(__name__)


def load_buffer(path: Path) -> Dict[str, List[Any]]:
    """Load a (possibly gzip-compressed) pickled replay buffer."""
    if not path.exists():
        raise FileNotFoundError(f"replay buffer not found: {path}")
    opener = gzip.open if path.suffix == ".gz" else open
    with opener(path, "rb") as f:
        buf = pickle.load(f)
    if not isinstance(buf, dict):
        raise ValueError(
            f"unexpected buffer type {type(buf).__name__}; "
            "expected dict with keys states / move_probs / values"
        )
    required = {"states", "move_probs", "values"}
    missing = required - set(buf.keys())
    if missing:
        raise ValueError(f"buffer missing required keys: {missing}")
    return buf


def stack_states(states: List[np.ndarray]) -> np.ndarray:
    """Stack list of (C, 11, 11) arrays into (N, C, 11, 11) float32."""
    arr = np.stack(states, axis=0).astype(np.float32, copy=False)
    if arr.ndim != 4 or arr.shape[-2:] != (11, 11):
        raise ValueError(f"states shape unexpected: {arr.shape}; want (N, C, 11, 11)")
    return arr


def stack_move_probs(probs: List[np.ndarray]) -> np.ndarray:
    """Stack list of (7433,) arrays into (N, 7433) float16.

    Keep float16 — the pretrain dataloader casts to float on load (see
    soft-target NLL path). Halves disk footprint vs float32.
    """
    arr = np.stack(probs, axis=0).astype(np.float16, copy=False)
    if arr.ndim != 2:
        raise ValueError(f"move_probs shape unexpected: {arr.shape}; want (N, total_moves)")
    return arr


def values_to_array(values: List[float]) -> np.ndarray:
    """Convert list of scalars to (N,) float32. Buffer stores values in
    [-1, 1] (rolled-out MCTS root values, sign-flipped per side-to-move).
    """
    arr = np.asarray(values, dtype=np.float32)
    if arr.ndim != 1:
        raise ValueError(f"values shape unexpected: {arr.shape}; want (N,)")
    if arr.size > 0:
        lo, hi = float(arr.min()), float(arr.max())
        if lo < -1.001 or hi > 1.001:
            logger.warning(
                f"values out of expected [-1, 1] range: min={lo:.3f} max={hi:.3f} "
                "(not an error — but the pretrain loader assumes this range)"
            )
    return arr


def write_mmap_dir(out_dir: Path, states: np.ndarray, policies: np.ndarray,
                   values: np.ndarray, policy_target: str) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    np.save(out_dir / "states.npy", states)
    np.save(out_dir / "values.npy", values)
    if policy_target == "soft":
        np.save(out_dir / "policies.npy", policies)
    elif policy_target == "argmax":
        policy_indices = policies.argmax(axis=1).astype(np.int32)
        np.save(out_dir / "policy_indices.npy", policy_indices)
    else:
        raise ValueError(f"unknown policy_target: {policy_target!r}")


def main() -> None:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--buffer", type=Path, required=True,
                   help="Path to replay_buffer.pkl(.gz)")
    p.add_argument("--output", type=Path, required=True,
                   help="Output directory for mmap-ready .npy files")
    p.add_argument("--policy-target", choices=["soft", "argmax"], default="soft",
                   help="Policy target schema. 'soft' (default) saves full "
                        "visit distributions to policies.npy — uses more "
                        "signal but ~7400× larger. 'argmax' saves move indices "
                        "to policy_indices.npy — smaller, CE-loss-compatible.")
    p.add_argument("--limit", type=int, default=None,
                   help="Optional cap on number of samples (for smoke tests). "
                        "Default: keep all.")
    args = p.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%H:%M:%S",
    )

    t0 = time.time()
    logger.info(f"Loading buffer from {args.buffer}")
    buf = load_buffer(args.buffer)
    n_total = len(buf["states"])
    if args.limit is not None and args.limit < n_total:
        logger.info(f"Truncating buffer from {n_total} → {args.limit} samples")
        states = buf["states"][: args.limit]
        move_probs = buf["move_probs"][: args.limit]
        values = buf["values"][: args.limit]
    else:
        states = buf["states"]
        move_probs = buf["move_probs"]
        values = buf["values"]

    logger.info(f"Stacking {len(states)} samples into npy arrays...")
    states_arr = stack_states(states)
    policies_arr = stack_move_probs(move_probs)
    values_arr = values_to_array(values)

    # Diagnostic: real phase mix via the encoder-aware decoder (the
    # buffer's stored `phases` field is unreliable for 15-channel runs
    # written before the trainer's decode_phase fix — see
    # EXPERIMENT_BACKLOG B1+B2+B3 Done entry, "phase-weight bug").
    try:
        from yinsh_ml.utils.encoding import decode_phase_from_state
        phase_counts: Dict[str, int] = {}
        # Sample up to 2000 states to keep this cheap; report fractions
        sample_n = min(2000, len(states_arr))
        idx = np.linspace(0, len(states_arr) - 1, sample_n).astype(int)
        for i in idx:
            ph = decode_phase_from_state(states_arr[i])
            phase_counts[ph] = phase_counts.get(ph, 0) + 1
        logger.info(
            f"Phase mix (sampled {sample_n}): "
            + ", ".join(f"{k}={v} ({v/sample_n:.1%})" for k, v in sorted(phase_counts.items()))
        )
    except Exception as e:
        logger.warning(f"Could not compute phase mix diagnostic: {e}")

    # Filter zero-policy rows. The supervisor's self-play adds dummy
    # zero policies for terminal positions and for some early-game
    # positions where MCTS produced no visit distribution. Training on
    # all-zero soft targets pushes the policy head toward uniform; drop
    # them.
    nonzero_mask = (policies_arr.astype(np.float32).sum(axis=1) > 1e-3)
    n_before = len(policies_arr)
    n_zero = n_before - int(nonzero_mask.sum())
    if n_zero > 0:
        logger.info(
            f"Filtering {n_zero}/{n_before} zero-policy rows "
            f"({n_zero/n_before:.1%} — dummies / terminal positions)"
        )
        states_arr = states_arr[nonzero_mask]
        policies_arr = policies_arr[nonzero_mask]
        values_arr = values_arr[nonzero_mask]
        logger.info(f"Kept {len(states_arr)} samples after filtering")

    logger.info(
        f"Shapes: states={states_arr.shape} dtype={states_arr.dtype}, "
        f"policies={policies_arr.shape} dtype={policies_arr.dtype}, "
        f"values={values_arr.shape} dtype={values_arr.dtype}"
    )
    total_gb = (states_arr.nbytes + policies_arr.nbytes + values_arr.nbytes) / 1e9
    logger.info(f"Total in-memory size: {total_gb:.2f} GB")

    logger.info(f"Writing {args.policy_target} schema to {args.output}/")
    write_mmap_dir(args.output, states_arr, policies_arr, values_arr, args.policy_target)

    # Verify the output reloads as mmap
    logger.info("Verifying outputs via mmap_mode='r' ...")
    for npy in sorted(args.output.glob("*.npy")):
        arr = np.load(npy, mmap_mode="r")
        logger.info(f"  {npy.name}: shape={arr.shape} dtype={arr.dtype}")
        del arr

    logger.info(f"Done in {time.time() - t0:.1f}s. Output: {args.output}/")


if __name__ == "__main__":
    main()
